name = "fastapi-depends"
repo = "fastapi"
entity = "Depends"
expected_files = [
  "docs_src/authentication_error_status_code/tutorial001_an_py310.py",
  "docs_src/background_tasks/tutorial002_an_py310.py",
  "docs_src/background_tasks/tutorial002_py310.py",
  "docs_src/bigger_applications/app_an_py310/main.py",
  "docs_src/bigger_applications/app_an_py310/routers/items.py",
  "docs_src/dependencies/tutorial001_02_an_py310.py",
  "docs_src/dependencies/tutorial001_an_py310.py",
  "docs_src/dependencies/tutorial001_py310.py",
  "docs_src/dependencies/tutorial002_an_py310.py",
  "docs_src/dependencies/tutorial002_py310.py",
  "docs_src/dependencies/tutorial003_an_py310.py",
  "docs_src/dependencies/tutorial003_py310.py",
  "docs_src/dependencies/tutorial004_an_py310.py",
  "docs_src/dependencies/tutorial004_py310.py",
  "docs_src/dependencies/tutorial005_an_py310.py",
  "docs_src/dependencies/tutorial005_py310.py",
  "docs_src/dependencies/tutorial006_an_py310.py",
  "docs_src/dependencies/tutorial006_py310.py",
  "docs_src/dependencies/tutorial008_an_py310.py",
  "docs_src/dependencies/tutorial008_py310.py",
  "docs_src/dependencies/tutorial008b_an_py310.py",
  "docs_src/dependencies/tutorial008b_py310.py",
  "docs_src/dependencies/tutorial008c_an_py310.py",
  "docs_src/dependencies/tutorial008c_py310.py",
  "docs_src/dependencies/tutorial008d_an_py310.py",
  "docs_src/dependencies/tutorial008d_py310.py",
  "docs_src/dependencies/tutorial008e_an_py310.py",
  "docs_src/dependencies/tutorial008e_py310.py",
  "docs_src/dependencies/tutorial011_an_py310.py",
  "docs_src/dependencies/tutorial011_py310.py",
  "docs_src/dependencies/tutorial012_an_py310.py",
  "docs_src/dependencies/tutorial012_py310.py",
  "docs_src/dependencies/tutorial013_an_py310.py",
  "docs_src/dependencies/tutorial014_an_py310.py",
  "docs_src/dependency_testing/tutorial001_an_py310.py",
  "docs_src/dependency_testing/tutorial001_py310.py",
  "docs_src/security/tutorial001_an_py310.py",
  "docs_src/security/tutorial001_py310.py",
  "docs_src/security/tutorial002_an_py310.py",
  "docs_src/security/tutorial002_py310.py",
  "docs_src/security/tutorial003_an_py310.py",
  "docs_src/security/tutorial003_py310.py",
  "docs_src/security/tutorial004_an_py310.py",
  "docs_src/security/tutorial004_py310.py",
  "docs_src/security/tutorial005_an_py310.py",
  "docs_src/security/tutorial005_py310.py",
  "docs_src/security/tutorial006_an_py310.py",
  "docs_src/security/tutorial006_py310.py",
  "docs_src/security/tutorial007_an_py310.py",
  "docs_src/security/tutorial007_py310.py",
  "docs_src/settings/app02_an_py310/main.py",
  "docs_src/settings/app02_py310/main.py",
  "docs_src/settings/app03_an_py310/main.py",
  "docs_src/settings/app03_py310/main.py",
  "docs_src/sql_databases/tutorial001_an_py310.py",
  "docs_src/sql_databases/tutorial001_py310.py",
  "docs_src/sql_databases/tutorial002_an_py310.py",
  "docs_src/sql_databases/tutorial002_py310.py",
  "docs_src/websockets_/tutorial002_an_py310.py",
  "docs_src/websockets_/tutorial002_py310.py",
  "fastapi/__init__.py",
  "fastapi/applications.py",
  "fastapi/dependencies/utils.py",
  "fastapi/param_functions.py",
  "fastapi/params.py",
  "fastapi/routing.py",
  "tests/benchmarks/test_general_performance.py",
  "tests/test_ambiguous_params.py",
  "tests/test_dependency_after_yield_raise.py",
  "tests/test_dependency_after_yield_streaming.py",
  "tests/test_dependency_after_yield_websockets.py",
  "tests/test_dependency_cache.py",
  "tests/test_dependency_class.py",
  "tests/test_dependency_contextmanager.py",
  "tests/test_dependency_contextvars.py",
  "tests/test_dependency_duplicates.py",
  "tests/test_dependency_overrides.py",
  "tests/test_dependency_partial.py",
  "tests/test_dependency_pep695.py",
  "tests/test_dependency_security_overrides.py",
  "tests/test_dependency_wrapped.py",
  "tests/test_dependency_yield_except_httpexception.py",
  "tests/test_dependency_yield_scope.py",
  "tests/test_dependency_yield_scope_websockets.py",
  "tests/test_depends_hashable.py",
  "tests/test_enforce_once_required_parameter.py",
  "tests/test_exception_handlers.py",
  "tests/test_filter_pydantic_sub_model_pv2.py",
  "tests/test_generic_parameterless_depends.py",
  "tests/test_http_connection_injection.py",
  "tests/test_include_router_defaults_overrides.py",
  "tests/test_param_in_path_and_dependency.py",
  "tests/test_repeated_cookie_headers.py",
  "tests/test_repeated_dependency_schema.py",
  "tests/test_response_change_status_code.py",
  "tests/test_response_dependency.py",
  "tests/test_security_api_key_cookie.py",
  "tests/test_security_api_key_cookie_description.py",
  "tests/test_security_api_key_cookie_optional.py",
  "tests/test_security_api_key_header.py",
  "tests/test_security_api_key_header_description.py",
  "tests/test_security_api_key_header_optional.py",
  "tests/test_security_api_key_query.py",
  "tests/test_security_api_key_query_description.py",
  "tests/test_security_api_key_query_optional.py",
  "tests/test_security_oauth2.py",
  "tests/test_security_oauth2_authorization_code_bearer_scopes_openapi.py",
  "tests/test_security_oauth2_authorization_code_bearer_scopes_openapi_simple.py",
  "tests/test_security_oauth2_optional.py",
  "tests/test_security_oauth2_optional_description.py",
  "tests/test_security_openid_connect.py",
  "tests/test_security_openid_connect_description.py",
  "tests/test_security_openid_connect_optional.py",
  "tests/test_security_scopes.py",
  "tests/test_security_scopes_sub_dependency.py",
  "tests/test_stringified_annotation_dependency.py",
  "tests/test_stringified_annotation_dependency_py314.py",
  "tests/test_stringified_annotations_simple.py",
  "tests/test_top_level_security_scheme_in_openapi.py",
  "tests/test_tutorial/test_dependencies/test_tutorial008.py",
  "tests/test_tutorial/test_dependencies/test_tutorial010.py",
  "tests/test_ws_dependencies.py",
  "tests/test_ws_router.py",
]
