name = "trpc-trpcerror"
repo = "trpc"
entity = "TRPCError"
expected_files = [
  "examples/.experimental/next-app-dir/src/server/trpc.ts",
  "examples/.test/diagnostics-big-router/src/server/trpc.ts",
  "examples/express-server/src/server.ts",
  "examples/fastify-server/src/server/router/routers/posts.ts",
  "examples/next-prisma-starter/src/server/routers/post.ts",
  "examples/next-prisma-websockets-starter/src/server/trpc.ts",
  "examples/next-sse-chat/src/server/trpc.ts",
  "packages/client/src/links/localLink.test.ts",
  "packages/next/src/app-dir/server.ts",
  "packages/react-query/test/__testHelpers.tsx",
  "packages/react-query/test/polymorphism.factory.tsx",
  "packages/react-query/test/polymorphism.subtyped-factory.tsx",
  "packages/server/src/@trpc/server/index.ts",
  "packages/server/src/adapters/next-app-dir/nextAppDirCaller.ts",
  "packages/server/src/adapters/next-app-dir/notFound.ts",
  "packages/server/src/adapters/next-app-dir/redirect.ts",
  "packages/server/src/adapters/next-app-dir/rethrowNextErrors.ts",
  "packages/server/src/adapters/next.ts",
  "packages/server/src/adapters/node-http/incomingMessageToRequest.ts",
  "packages/server/src/adapters/ws.ts",
  "packages/server/src/unstable-core-do-not-import/error/TRPCError.ts",
  "packages/server/src/unstable-core-do-not-import/error/formatter.ts",
  "packages/server/src/unstable-core-do-not-import/error/getErrorShape.ts",
  "packages/server/src/unstable-core-do-not-import/http/contentType.ts",
  "packages/server/src/unstable-core-do-not-import/http/getHTTPStatusCode.ts",
  "packages/server/src/unstable-core-do-not-import/http/parseConnectionParams.ts",
  "packages/server/src/unstable-core-do-not-import/http/resolveResponse.ts",
  "packages/server/src/unstable-core-do-not-import/http/types.ts",
  "packages/server/src/unstable-core-do-not-import/middleware.ts",
  "packages/server/src/unstable-core-do-not-import/procedure.ts",
  "packages/server/src/unstable-core-do-not-import/procedureBuilder.test.ts",
  "packages/server/src/unstable-core-do-not-import/procedureBuilder.ts",
  "packages/server/src/unstable-core-do-not-import/router.ts",
  "packages/tanstack-react-query/test/polymorphism.factory.tsx",
  "packages/tests/server/TRPCError.test.ts",
  "packages/tests/server/adapters/express.test.tsx",
  "packages/tests/server/adapters/standalone.test.ts",
  "packages/tests/server/batching.test.ts",
  "packages/tests/server/caller.test.ts",
  "packages/tests/server/createCaller.test.ts",
  "packages/tests/server/errorFormatting.test.ts",
  "packages/tests/server/errors.test.ts",
  "packages/tests/server/getRawInput.test.ts",
  "packages/tests/server/httpSubscriptionLink.headers.retryLink.test.ts",
  "packages/tests/server/index.test.ts",
  "packages/tests/server/regression/issue-2856-middleware-infer.test.ts",
  "packages/tests/server/regression/issue-3351-TRPCError.test.ts",
  "packages/tests/server/regression/issue-4217-throw-non-errors.test.ts",
  "packages/tests/server/regression/issue-4321-context-union-inference.test.ts",
  "packages/tests/server/regression/issue-4527-nested-middleware-root-context.test.ts",
  "packages/tests/server/regression/issue-5037-context-inference.test.ts",
  "packages/tests/server/streaming.test.ts",
  "packages/tests/server/transformer.test.ts",
  "packages/tests/server/validators.test.ts",
  "packages/tests/server/websockets.test.ts",
  "packages/tests/showcase/tinyrpc.test.ts",
]
