name = "trpc-inittrpc"
repo = "trpc"
entity = "initTRPC"
expected_files = [
  "examples/.experimental/next-app-dir/src/app/posts/_lib/trpc.ts",
  "examples/.experimental/next-app-dir/src/server/trpc.ts",
  "examples/.test/diagnostics-big-router/src/server/trpc.ts",
  "examples/.test/internal-types-export/src/server.ts",
  "examples/.test/monotest-trpc/src/trpc.ts",
  "examples/.test/ssg-infinite-serialization/src/server/trpc.ts",
  "examples/.test/ssg/src/server/trpc.ts",
  "examples/bun/src/router.ts",
  "examples/cloudflare-workers/src/router.ts",
  "examples/deno-deploy/src/router.ts",
  "examples/express-minimal/src/router.ts",
  "examples/express-server/src/server.ts",
  "examples/fastify-server/src/server/router/trpc.ts",
  "examples/lambda-api-gateway-streaming/src/server.ts",
  "examples/lambda-api-gateway/src/server.ts",
  "examples/lambda-url/src/server.ts",
  "examples/lazy-load/src/server/trpc.ts",
  "examples/minimal-content-types/server/index.ts",
  "examples/minimal-react/server/index.ts",
  "examples/minimal/src/server/trpc.ts",
  "examples/next-big-router/src/server/trpc.ts",
  "examples/next-edge-runtime/src/server/trpc.ts",
  "examples/next-formdata/src/server/trpc.ts",
  "examples/next-minimal-starter/src/server/trpc.ts",
  "examples/next-prisma-starter/src/server/trpc.ts",
  "examples/next-prisma-todomvc/src/server/trpc.ts",
  "examples/next-prisma-websockets-starter/src/server/trpc.ts",
  "examples/next-sse-chat/src/server/trpc.ts",
  "examples/next-websockets-encoder/src/server/trpc.ts",
  "examples/nuxt/server/trpc/init.ts",
  "examples/openapi-codegen/src/server/trpc.ts",
  "examples/soa/server-lib/index.ts",
  "examples/standalone-server/src/server.ts",
  "examples/vercel-edge-runtime/src/router.ts",
  "packages/client/src/links/localLink.test.ts",
  "packages/next/src/app-dir/client.test.tsx",
  "packages/next/test/issue-4130-ssr-different-transformers.test.tsx",
  "packages/openapi/test/routers/amazonIonRouter.ts",
  "packages/openapi/test/routers/appRouter.ts",
  "packages/openapi/test/routers/descriptionsRouter.ts",
  "packages/openapi/test/routers/edgeCaseRouter.ts",
  "packages/openapi/test/routers/errorFormatterRouter.ts",
  "packages/openapi/test/routers/mongoEjsonRouter.ts",
  "packages/openapi/test/routers/superjsonRouter.ts",
  "packages/openapi/test/schemaExtraction.test.ts",
  "packages/react-query/test/__testHelpers.tsx",
  "packages/react-query/test/abortOnUnmount.test.tsx",
  "packages/react-query/test/createClient.test.tsx",
  "packages/react-query/test/dehydrate.test.tsx",
  "packages/react-query/test/errors.test.tsx",
  "packages/react-query/test/formData.test.tsx",
  "packages/react-query/test/getQueryKey.test.tsx",
  "packages/react-query/test/invalidateRouters.test.tsx",
  "packages/react-query/test/multiple-trpc-providers.test.tsx",
  "packages/react-query/test/mutationkey.test.tsx",
  "packages/react-query/test/octetStreams.test.tsx",
  "packages/react-query/test/offline.test.tsx",
  "packages/react-query/test/overrides.test.tsx",
  "packages/react-query/test/polymorphism.common.tsx",
  "packages/react-query/test/queryClientDefaults.test.tsx",
  "packages/react-query/test/queryOptions.test.tsx",
  "packages/react-query/test/regression/issue-2942-useInfiniteQuery-setData.test.tsx",
  "packages/react-query/test/regression/issue-2996-defined-data.test.tsx",
  "packages/react-query/test/regression/issue-3455-56-invalidate-queries.test.tsx",
  "packages/react-query/test/regression/issue-3461-reserved-properties.test.tsx",
  "packages/react-query/test/regression/issue-4360-useInfiniteQuery-placeHolderData.test.tsx",
  "packages/react-query/test/regression/issue-4486-initialData-types.test.tsx",
  "packages/react-query/test/regression/issue-4519-invalid-select-as-transform.test.tsx",
  "packages/react-query/test/regression/issue-5357-input-always-required.test.tsx",
  "packages/react-query/test/regression/issue-5808-proxy-in-dep-array.test.tsx",
  "packages/react-query/test/rsc-prefetch.test.tsx",
  "packages/react-query/test/ssg.test.ts",
  "packages/react-query/test/ssgExternal.test.ts",
  "packages/react-query/test/trpc-options.test.tsx",
  "packages/react-query/test/useMutation.test.tsx",
  "packages/react-query/test/useQueries.test.tsx",
  "packages/react-query/test/useQuery.test.tsx",
  "packages/react-query/test/useSubscription.test.tsx",
  "packages/react-query/test/useSuspenseInfiniteQuery.test.tsx",
  "packages/react-query/test/useSuspenseQueries.test.tsx",
  "packages/react-query/test/useSuspenseQuery.test.tsx",
  "packages/react-query/test/useUtils.test.tsx",
  "packages/server/src/@trpc/server/index.ts",
  "packages/server/src/adapters/next-app-dir.test.ts",
  "packages/server/src/unstable-core-do-not-import/clientish/inference.test.ts",
  "packages/server/src/unstable-core-do-not-import/initTRPC.test.ts",
  "packages/server/src/unstable-core-do-not-import/procedureBuilder.test.ts",
  "packages/server/src/unstable-core-do-not-import/router.mergeRouters.test.ts",
  "packages/server/src/unstable-core-do-not-import/router.test.ts",
  "packages/tanstack-react-query/test/client.test.tsx",
  "packages/tanstack-react-query/test/infiniteQueryOptions.test.tsx",
  "packages/tanstack-react-query/test/multipleTrpcProviders.test.tsx",
  "packages/tanstack-react-query/test/mutationOptions.test.tsx",
  "packages/tanstack-react-query/test/polymorphism.common.tsx",
  "packages/tanstack-react-query/test/queryKeyable.test.tsx",
  "packages/tanstack-react-query/test/queryOptions.test.tsx",
  "packages/tanstack-react-query/test/skipToken.test.tsx",
  "packages/tanstack-react-query/test/useSubscription.test.tsx",
  "packages/tests/server/abortQuery.test.ts",
  "packages/tests/server/adapters/awsLambda.test.tsx",
  "packages/tests/server/adapters/express.test.tsx",
  "packages/tests/server/adapters/fastify.test.ts",
  "packages/tests/server/adapters/fetch.test.ts",
  "packages/tests/server/adapters/next.test.ts",
  "packages/tests/server/adapters/standalone.http2.test.ts",
  "packages/tests/server/adapters/standalone.test.ts",
  "packages/tests/server/batching.test.ts",
  "packages/tests/server/callRouter.test.ts",
  "packages/tests/server/caller.test.ts",
  "packages/tests/server/children.test.ts",
  "packages/tests/server/contentTypeHeaders.test.ts",
  "packages/tests/server/createCaller.test.ts",
  "packages/tests/server/errorFormatting.test.ts",
  "packages/tests/server/errors.test.ts",
  "packages/tests/server/getRawInput.test.ts",
  "packages/tests/server/getUntypedClient.test.ts",
  "packages/tests/server/headers.test.tsx",
  "packages/tests/server/httpSubscriptionLink.headers.retryLink.test.ts",
  "packages/tests/server/httpSubscriptionLink.memory.test.ts",
  "packages/tests/server/httpSubscriptionLink.test.ts",
  "packages/tests/server/index.test.ts",
  "packages/tests/server/inferenceHelpers.test.ts",
  "packages/tests/server/input.test.ts",
  "packages/tests/server/isDev.test.ts",
  "packages/tests/server/jsonify.test.ts",
  "packages/tests/server/links.test.ts",
  "packages/tests/server/meta.test.ts",
  "packages/tests/server/methodOverride.test.ts",
  "packages/tests/server/middlewares.test.ts",
  "packages/tests/server/outputParser.test.ts",
  "packages/tests/server/rawFetch.test.tsx",
  "packages/tests/server/regression/issue-2506-headers-throwing.test.ts",
  "packages/tests/server/regression/issue-2540-undefined-mutation.test.ts",
  "packages/tests/server/regression/issue-2842-createSSGHelpers-promise.test.ts",
  "packages/tests/server/regression/issue-2856-middleware-infer.test.ts",
  "packages/tests/server/regression/issue-3453-meta-interface.test.ts",
  "packages/tests/server/regression/issue-3710-client.test.ts",
  "packages/tests/server/regression/issue-4049-stripped-undefined.test.tsx",
  "packages/tests/server/regression/issue-4217-throw-non-errors.test.ts",
  "packages/tests/server/regression/issue-4321-context-union-inference.test.ts",
  "packages/tests/server/regression/issue-4527-nested-middleware-root-context.test.ts",
  "packages/tests/server/regression/issue-4645-inferProcedureOutput.test.ts",
  "packages/tests/server/regression/issue-4673-url-encoded-batching.test.ts",
  "packages/tests/server/regression/issue-4783-charset.test.ts",
  "packages/tests/server/regression/issue-4947-merged-middleware-inputs.test.ts",
  "packages/tests/server/regression/issue-5020-inference-middleware.test.ts",
  "packages/tests/server/regression/issue-5034-input-with-index-signature.test.ts",
  "packages/tests/server/regression/issue-5037-context-inference.test.ts",
  "packages/tests/server/regression/issue-5056-input-parser-standalone-mw-inference.test.ts",
  "packages/tests/server/regression/issue-5297-description-key-on-input-turns-to-void.test.ts",
  "packages/tests/server/regression/issue-5945-stream-null.test.ts",
  "packages/tests/server/regression/issue-6461-stream-error.test.ts",
  "packages/tests/server/regression/serializable-inference.test.tsx",
  "packages/tests/server/responseMeta.test.ts",
  "packages/tests/server/routerMeta.test.ts",
  "packages/tests/server/smoke.test.ts",
  "packages/tests/server/streaming.test.ts",
  "packages/tests/server/transformer.test.ts",
  "packages/tests/server/validators.test.ts",
  "packages/tests/server/websockets.encoder.test.ts",
  "packages/tests/server/websockets.memory.test.ts",
  "packages/tests/server/websockets.test.ts",
  "packages/tests/showcase/dataloader.test.ts",
  "packages/tests/showcase/tinyrpc.test.ts",
  "packages/upgrade/test/__fixtures__/hooks/basic.trpc.tsx",
  "packages/upgrade/test/__fixtures__/hooks/existingRqMix.trpc.tsx",
  "packages/upgrade/test/__fixtures__/hooks/multipleFunctions.trpc.tsx",
  "packages/upgrade/test/__fixtures__/hooks/optimistic-update.trpc.tsx",
  "packages/upgrade/test/__fixtures__/hooks/reactContext.trpc.tsx",
  "packages/upgrade/test/__fixtures__/hooks/suspenseDestructuring.trpc.tsx",
  "packages/upgrade/test/__fixtures__/hooks/utilities.trpc.tsx",
  "packages/upgrade/test/__fixtures__/hooks/withInvalidate.trpc.tsx",
  "packages/upgrade/test/__fixtures__/provider/basic.trpc.tsx",
]
